### ISSUE TITLE
XML issues

### ISSUE THREAD

**Issue by ingbrzy** [cjhyuky/MA-XML-MIUI10-KOREAN#1]
https://translators.xiaomi.eu/XML_MIUI10-Korean-ko.html

**Comment by bradly1** [comment]
96202c06957b52707267d51fb59e7c9e54d5e5f9

**Comment by ingbrzy** [comment]
https://translators.xiaomi.eu/XML_MIUI10-Korean-ko.html

**Comment by bradly1** [comment]
54a11fc4100c787abc24756a088d8c5432236c14
448cc5d9d19ac45cfd52b11e7b9803a9786ea540
2f53f7afbde08e9d0a2b5b5b1df4bf89b2880f3d

**Comment by ingbrzy** [comment]
https://translators.xiaomi.eu/XML_MIUI10-Korean-ko.html

**Comment by bradly1** [comment]
4e063b7f84c02e127d0e9ca36884d1409ae32f76
sorry...

**Comment by ingbrzy** [comment]
https://translators.xiaomi.eu/XML_MIUI10-Korean-ko.html
