### ISSUE TITLE
MIUI Calendar Widget FC

### ISSUE THREAD

**Issue by ingbrzy** [cjhyuky/MA-XML-MIUI10-KOREAN#4]
https://xiaomi.eu/community/threads/9-1-24-26.48919/page-14#post-470428

**Comment by bradly1** [comment]
We identified the issue. However, it will take some time to correct the issue since it has occurred from a long time ago. We will fix the issue as soon as possible.

**Comment by cjhyuky** [comment]
We fixed it!
